apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres-db:5432
    database: hk_bus
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
    editable: true
