apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres
    url: postgres:5432
    database: hkbus
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    isDefault: false

  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
